---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: medishift-postgres
  namespace: medishift-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medishift-postgres
  serviceName: medishift-postgres
  template:
    metadata:
      labels:
        app: medishift-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: medishift-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medishift-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: medishift-secrets
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medishift
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - medishift
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: medishift-postgres-prod-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: medishift-postgres
  namespace: medishift-prod
spec:
  selector:
    app: medishift-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
