apiVersion: v1
kind: Secret
metadata:
  name: medishift-secrets
  namespace: medishift-prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://medishift:medishift123@medishift-postgres.medishift-prod.svc.cluster.local:5432/medishift
  JWT_SECRET: medishift_jwt_secret_key_2024
  POSTGRES_USER: medishift
  POSTGRES_PASSWORD: medishift123
  POSTGRES_DB: medishift
