apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: medishift-kv-secrets
  namespace: medishift-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "true" # Enables Azure Workload Identity integration
    keyvaultName: "kv-medishift-prod-152xet" # Replace with Key Vault Name output from Terraform
    tenantId: "ffdb5413-63c8-40ec-a158-c5ad34880e3d" # Replace with Tenant ID output from Terraform
    clientID: "d249092b-0f4b-4368-a2c3-83891d2afc1e" # Replace with Workload Identity client ID output
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-db
          objectType: secret
  secretObjects:
    - secretName: medishift-secrets
      type: Opaque
      data:
        - key: DATABASE_URL
          objectName: database-url
        - key: JWT_SECRET
          objectName: jwt-secret
        - key: POSTGRES_USER
          objectName: postgres-user
        - key: POSTGRES_PASSWORD
          objectName: postgres-password
        - key: POSTGRES_DB
          objectName: postgres-db
