apiVersion: v1
kind: ConfigMap
metadata:
  name: medishift-config
  namespace: medishift-dev
data:
  NODE_ENV: development
  AUTH_SERVICE_URL: http://medishift-auth-service.medishift-dev.svc.cluster.local:3001
  STAFF_SERVICE_URL: http://medishift-staff-service.medishift-dev.svc.cluster.local:3002
  SHIFT_SERVICE_URL: http://medishift-shift-service.medishift-dev.svc.cluster.local:3003
  LEAVE_SERVICE_URL: http://medishift-leave-service.medishift-dev.svc.cluster.local:3004
