apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medishift-auth-hpa
  namespace: medishift-${environment}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medishift-auth-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medishift-staff-hpa
  namespace: medishift-${environment}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medishift-staff-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medishift-shift-hpa
  namespace: medishift-${environment}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medishift-shift-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medishift-leave-hpa
  namespace: medishift-${environment}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medishift-leave-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medishift-frontend-hpa
  namespace: medishift-${environment}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medishift-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
