---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: medishift-postgres-prod-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.31.26.181
    path: /srv/nfs/medishift-prod

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medishift-postgres-prod-pvc
  namespace: medishift-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: medishift-postgres-prod-pv
